### PR TITLE
Fix issue : Entry module cannot be external

### LINKED ISSUE #20: Entry module cannot be external
If i want to flag as external all modules not in the src directory with this rollup configuration file
```js
import multiEntry from "rollup-plugin-multi-entry";

export default {
	entry: "tests/**/*.js"
	format: "cjs",
	plugins: [
		multiEntry ()
	],
	external: id => !(/src\//.test(id)),
	dest: "dist/tests.js"
};
```
then rollup fails with 

> Entry module cannot be external

because the entry point is replaced with `rollup-plugin-multi-entry:entry-point` and the external function doesn't match

### PR DESCRIPTION
**Pull request by CodeTroopers**
Fix #20

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Thanks! Could you add tests please? Let me know if you need any help with that.

**Comment by CodeTroopers** [comment]
I added 2 tests but i also updated the rollup dependency to v0.45.2 because the issue was not exactly the same with the older version. So i updated all tests because bundle.generate return a promise instead of an object

**Comment by CodeTroopers** [comment]
It seem that there is problem with tab/spaces mixing in the commit. Could you fix it on the merge?

**Comment by shellscape** [comment]
@eventualbuddha @CodeTroopers  I'd like to begin the process of moving this plugin to our new monorepo. To do that we have to get the outstanding PRs resolved. Any chance you all can wrap this one up this week?

**Comment by CodeTroopers** [comment]
@eventualbuddha Could you merge this PR?

**Comment by shellscape** [comment]
@CodeTroopers we're going to need to add a test that fails when it should. e.g. `it.throws` a test that catches a failing case. all plugins are moving to Rollup@^1.20.0 now as well, so we should bump the version to `^1.20.0` in package json and run against that. That's important since you mentioned an older version not having the same problems. There wouldn't be much point to testing against an old version if the next we're going to release will be requiring the current stable version.

**Comment by CodeTroopers** [comment]
@shellscape This PR is a fix for an issue. So upgrade of dependencies or adding additional tests to ensure the integrity of the library should be merged from another PR

**Comment by shellscape** [comment]
I understand your position. Thanks for your work on this PR, but unfortunately we'll have to pass on it at this time. We'll be moving this plugin to the new monorepo soon, and we'd welcome a renewed submission there once that happens.

**Pull request closed without merging**
