### PR TITLE
fix: make default exports work

### PR DESCRIPTION
**Pull request by mikob**
Here is a hacky start to make default exports work. If you think this is worth fixing correctly, what approach do you think would be best? Eg. one heavyweight solution would be to parse with acorn and look at the AST for a default export. Wanted to start with simple+working before diving into a heavier solution.

#12

### CODE REVIEW

**Comment by shellscape** [comment]
@eventualbuddha @mikob I'd like to begin the process of moving this plugin to our new monorepo. To do that we have to get the outstanding PRs resolved. Any chance you all can wrap this one up this week?

**Comment by mikob** [comment]
@eventualbuddha is this a feature you would be interested in having by default? I'm still using it, personally.

**Comment by eventualbuddha** [comment]
I think it’s probably a good idea, but I can’t say I have any real investment in this repo anymore.

**Comment by shellscape** [comment]
Thanks for following up @eventualbuddha.

@mikob if it's cool with you, I'd like you to hang onto your fork and merge the changes into our monorepo when that move is complete. Does that sound good?

**Comment by mikob** [comment]
@shellscape it's fine with me, but I think it's a bad idea - what I wrote is very hacky. I wouldn't call it suitable for mainstream yet.

**Comment by shellscape** [comment]
Fair enough 😄 We'll close this for now, but we're open to the feature in @rollup/plugin-multi-entry

**Pull request closed without merging**
